spring:
  application:
    name: Invest_app
    
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
logging:
  level:
    org:
      springframework:
        security: DEBUG