spring:
  application:
    name: Invest_app
    main:
     allow-bean-definition-overriding: true
     
     mail:
      host: smtp.gmail.com
      port: 587
      username: chaitrams2905@gmail.com
      password: Chaitra@2912
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    default-encoding: UTF-8
    
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
logging:
  level:
    org:
      springframework:
        security: DEBUG